name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload site artifact
        uses: withastro/action@v2
        with:
          path: ./docs
          package-manager: pnpm@latest

  Deploy:
    needs: Build
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4